# These are supported funding model platforms

github: alexlee2046
# ko_fi: # Replace with a single Ko-fi username
# open_collective: # Replace with a single Open Collective username
# custom: ['https://www.example.com/donate']
