'use client';

import React, { useState } from 'react';
import { useRouter } from 'next/navigation';
import { useTranslations } from 'next-intl';
import { motion } from 'framer-motion';
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Card } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { ArrowLeft, Sparkles, Layout, FileCode, Loader2, ArrowRight } from "lucide-react";
import { createProject } from "@/lib/actions/projects";
import { toast } from "sonner";
import { Link } from '@/components/link';

export default function CreateProjectPage() {
    const router = useRouter();
    const t = useTranslations('dashboard'); // Assuming dashboard keys are relevant, or use 'common'
    const [isLoading, setIsLoading] = useState(false);
    const [mode, setMode] = useState<'blank' | 'ai' | 'import'>('ai');
    const [name, setName] = useState('');
    const [description, setDescription] = useState('');

    const handleCreate = async () => {
        if (!name.trim()) {
            toast.error("Please enter a project name");
            return;
        }

        setIsLoading(true);
        try {
            // "generated by" is used as the description/prompt in the current simple implementation
            const prompt = mode === 'ai' ? description : (mode === 'blank' ? 'Blank Project' : 'Imported Project');

            const newProject = await createProject(name, prompt);

            if (newProject?.id) {
                toast.success("Project created successfully!");
                // Redirect to Studio
                router.push(`/studio/${newProject.id}`);
            } else {
                throw new Error("Failed to create project record");
            }
        } catch (error: any) {
            console.error("Creation failed:", error);
            toast.error("Failed to create project: " + error.message);
        } finally {
            setIsLoading(false);
        }
    };

    return (
        <div className="min-h-screen bg-gradient-to-br from-background via-muted/50 to-background flex flex-col">
            {/* Header */}
            <header className="h-16 border-b bg-background/50 backdrop-blur-sm flex items-center px-4 md:px-8 sticky top-0 z-10">
                <Button variant="ghost" size="sm" asChild className="gap-2 text-muted-foreground hover:text-foreground">
                    <Link href="/dashboard">
                        <ArrowLeft className="h-4 w-4" />
                        Back to Dashboard
                    </Link>
                </Button>
            </header>

            <main className="flex-1 flex items-center justify-center p-4 md:p-8">
                <div className="w-full max-w-5xl grid lg:grid-cols-2 gap-8 lg:gap-16 items-center">

                    {/* Left: Content */}
                    <div className="space-y-8">
                        <div>
                            <h1 className="text-4xl font-bold tracking-tight mb-3 bg-clip-text text-transparent bg-gradient-to-r from-primary to-purple-600">
                                Start a New Project
                            </h1>
                            <p className="text-lg text-muted-foreground">
                                Bring your ideas to life. Choose how you want to start building.
                            </p>
                        </div>

                        <div className="space-y-6">
                            <div className="grid gap-2">
                                <Label htmlFor="name" className="text-base font-medium">Project Name</Label>
                                <Input
                                    id="name"
                                    placeholder="e.g., My Awesome Portfolio"
                                    value={name}
                                    onChange={(e) => setName(e.target.value)}
                                    className="h-12 text-lg"
                                    autoFocus
                                />
                            </div>

                            {/* Mode Selection Cards */}
                            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                                <ModeCard
                                    active={mode === 'ai'}
                                    onClick={() => setMode('ai')}
                                    icon={Sparkles}
                                    title="AI Generator"
                                    description="Describe your vision, let AI handle the rest."
                                />
                                <ModeCard
                                    active={mode === 'blank'}
                                    onClick={() => setMode('blank')}
                                    icon={Layout}
                                    title="Blank Canvas"
                                    description="Start from scratch with a clean slate."
                                />
                                <ModeCard
                                    active={mode === 'import'}
                                    onClick={() => setMode('import')}
                                    icon={FileCode}
                                    title="Import"
                                    description="Import HTML or an existing site."
                                />
                            </div>

                            {/* Dynamic Input based on Mode */}
                            <motion.div
                                initial={false}
                                animate={{ height: 'auto', opacity: 1 }}
                                className="space-y-4"
                            >
                                {mode === 'ai' && (
                                    <div className="space-y-2">
                                        <Label htmlFor="description" className="text-base font-medium flex items-center gap-2">
                                            <Sparkles className="h-4 w-4 text-purple-500" />
                                            Describe your website
                                        </Label>
                                        <Textarea
                                            id="description"
                                            placeholder="A modern landing page for a crypto DAO with a dark theme, hero section with 3D graphics, and a feature grid..."
                                            value={description}
                                            onChange={(e) => setDescription(e.target.value)}
                                            className="min-h-[120px] resize-none text-base p-4"
                                        />
                                    </div>
                                )}
                                {mode === 'import' && (
                                    <div className="p-4 rounded-lg bg-blue-50/50 dark:bg-blue-950/20 border border-blue-100 dark:border-blue-900 text-sm text-blue-600 dark:text-blue-400">
                                        You'll be able to paste your HTML code or URL after creating the project.
                                    </div>
                                )}
                            </motion.div>

                            <Button
                                size="lg"
                                className="w-full h-12 text-base font-medium bg-gradient-to-r from-primary to-purple-600 hover:from-primary/90 hover:to-purple-600/90 shadow-lg shadow-primary/20 transition-all"
                                onClick={handleCreate}
                                disabled={isLoading}
                            >
                                {isLoading ? (
                                    <>
                                        <Loader2 className="mr-2 h-5 w-5 animate-spin" />
                                        Creating...
                                    </>
                                ) : (
                                    <>
                                        Create Project
                                        <ArrowRight className="ml-2 h-5 w-5" />
                                    </>
                                )}
                            </Button>
                        </div>
                    </div>

                    {/* Right: Visual Decoration */}
                    <div className="hidden lg:block relative">
                        <div className="absolute inset-0 bg-gradient-to-tr from-purple-500/20 to-blue-500/20 blur-3xl rounded-full" />
                        <div className="relative bg-background/80 backdrop-blur-xl border rounded-2xl shadow-2xl p-6 overflow-hidden">
                            <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-transparent via-purple-500 to-transparent opacity-50" />

                            {/* Mock Preview based on mode */}
                            <div className="space-y-6 opacity-80 pointer-events-none select-none">
                                <div className="flex items-center gap-4 border-b pb-4">
                                    <div className="w-3 h-3 rounded-full bg-red-400" />
                                    <div className="w-3 h-3 rounded-full bg-yellow-400" />
                                    <div className="w-3 h-3 rounded-full bg-green-400" />
                                    <div className="flex-1 bg-muted/50 h-6 rounded-md mx-4" />
                                </div>

                                {mode === 'ai' ? (
                                    <div className="space-y-4 animate-pulse">
                                        <div className="h-32 bg-muted rounded-lg w-full" />
                                        <div className="grid grid-cols-3 gap-4">
                                            <div className="h-24 bg-muted/80 rounded-lg" />
                                            <div className="h-24 bg-muted/80 rounded-lg" />
                                            <div className="h-24 bg-muted/80 rounded-lg" />
                                        </div>
                                    </div>
                                ) : mode === 'blank' ? (
                                    <div className="flex items-center justify-center h-48 border-2 border-dashed border-muted-foreground/25 rounded-lg">
                                        <span className="text-muted-foreground">Empty Canvas</span>
                                    </div>
                                ) : (
                                    <div className="space-y-2 font-mono text-xs text-muted-foreground">
                                        <div className="pl-4 border-l-2 border-blue-500/50">&lt;div class="hero"&gt;</div>
                                        <div className="pl-8 border-l-2 border-blue-500/50">&lt;h1&gt;Imported Site&lt;/h1&gt;</div>
                                        <div className="pl-4 border-l-2 border-blue-500/50">&lt;/div&gt;</div>
                                    </div>
                                )}
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    );
}

function ModeCard({ active, onClick, icon: Icon, title, description }: { active: boolean, onClick: () => void, icon: any, title: string, description: string }) {
    return (
        <div
            onClick={onClick}
            className={`
                cursor-pointer p-4 rounded-xl border transition-all duration-200 text-left
                ${active
                    ? 'border-purple-500/50 bg-purple-500/5 ring-1 ring-purple-500/20 shadow-sm'
                    : 'border-border bg-card hover:bg-muted/50 hover:border-border/80'
                }
            `}
        >
            <div className={`p-2 rounded-lg w-fit mb-3 ${active ? 'bg-purple-500 text-white' : 'bg-muted text-muted-foreground'}`}>
                <Icon className="h-5 w-5" />
            </div>
            <h3 className={`font-medium mb-1 ${active ? 'text-primary' : 'text-foreground'}`}>{title}</h3>
            <p className="text-xs text-muted-foreground leading-relaxed">
                {description}
            </p>
        </div>
    );
}
