import React from 'react';
import Link from 'next/link';
import { Button } from "@/components/ui/button";
import { Undo, Redo, Share, Play, ArrowLeft, Save, Globe, Sparkles, ChevronRight } from "lucide-react";
import { useStudioStore } from "@/lib/store";
import { PublishModal } from "@/components/studio/PublishModal";
import { ShareModal } from "@/components/studio/ShareModal";
import { PublishToCommunityModal } from "@/components/studio/PublishToCommunityModal";
import { toast } from "sonner";
import { motion } from "framer-motion";

export function Toolbar() {
  const { undo, redo, past, future, currentProject, setCurrentProject, htmlContent } = useStudioStore();
  const [saving, setSaving] = React.useState(false);

  const handleSave = async () => {
    try {
      setSaving(true);
      const { updateProject, createProject } = await import("@/lib/actions/projects");

      if (currentProject?.id) {
        await updateProject(currentProject.id, { html: htmlContent });
        toast.success("Project saved");
      } else {
        const newProject = await createProject("Untitled Project", "Generated by Dao123");
        setCurrentProject(newProject);
        // Save content immediately after creation
        await updateProject(newProject.id, { html: htmlContent });
        toast.success("Project created and saved");
        // Update URL to include the new project ID
        window.history.replaceState(null, '', `/studio/${newProject.id}`);
      }
    } catch (error: any) {
      console.error(error);
      toast.error("Failed to save: " + error.message);
    } finally {
      setSaving(false);
    }
  };

  return (
    <div className="h-16 border-b border-border/40 bg-background/80 backdrop-blur-md flex items-center justify-between px-6 sticky top-0 z-50">
      <div className="flex items-center gap-4">
        <Button variant="ghost" size="icon" asChild title="返回 Dashboard" className="rounded-full hover:bg-primary/10 hover:text-primary transition-colors">
          <Link href="/dashboard">
            <ArrowLeft className="h-5 w-5" />
          </Link>
        </Button>

        <div className="flex items-center gap-2">
          <div className="h-8 w-8 rounded-lg bg-primary/10 flex items-center justify-center text-primary">
            <Sparkles className="h-4 w-4" />
          </div>
          <span className="font-bold text-lg tracking-tight">Studio</span>
          <ChevronRight className="h-4 w-4 text-muted-foreground" />
          <span className="text-sm text-muted-foreground">Untitled Project</span>
        </div>

        <div className="h-6 w-px bg-border/50 mx-2" />

        <div className="flex items-center gap-1">
          <Button
            variant="ghost"
            size="icon"
            title="撤销"
            onClick={undo}
            disabled={past.length === 0}
            className="rounded-full"
          >
            <Undo className="h-4 w-4" />
          </Button>
          <Button
            variant="ghost"
            size="icon"
            title="重做"
            onClick={redo}
            disabled={future.length === 0}
            className="rounded-full"
          >
            <Redo className="h-4 w-4" />
          </Button>
        </div>
      </div>

      <div className="flex items-center gap-3">
        <Button
          variant="ghost"
          size="sm"
          onClick={handleSave}
          className="rounded-full"
        >
          <Save className="h-4 w-4 mr-2" />
          保存
        </Button>

        <PublishToCommunityModal>
          <Button variant="outline" size="sm" className="rounded-full border-primary/20 hover:bg-primary/5 hover:text-primary">
            <Globe className="h-4 w-4 mr-2" />
            发布到广场
          </Button>
        </PublishToCommunityModal>

        <ShareModal>
          <Button variant="outline" size="sm" className="rounded-full border-primary/20 hover:bg-primary/5 hover:text-primary">
            <Share className="h-4 w-4 mr-2" />
            分享
          </Button>
        </ShareModal>

        <PublishModal>
          <Button size="sm" className="rounded-full px-6 shadow-lg shadow-primary/20 hover:shadow-primary/30 transition-all">
            <Play className="h-4 w-4 mr-2" />
            发布上线
          </Button>
        </PublishModal>
      </div>
    </div>
  );
}
